In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor
import pickle

/home/wendao/.conda/envs/automl/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
with open("TZ-Y_ssm_evo256.pickle", 'rb') as f:
    X_test, y_test = pickle.load(f)

In [3]:
predictor = TabularPredictor.load("AutogluonModels/ag-20220629_024330/")

In [4]:
testset = pd.DataFrame(X_test)
predictions = predictor.predict_proba(testset)

In [5]:
testset

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,-0.9,0.3,0.17,0.12,-0.03,-0.26,0.1,-0.04,1.15,-0.07,...,0.482652,-0.636783,0.471298,0.220211,0.234336,-0.743683,-0.34185,-0.082577,0.478921,0.223596
1,-0.93,0.21,0.19,0.12,-0.03,-0.26,0.1,-0.04,0.99,-0.07,...,0.494008,-0.638062,0.470645,0.220511,0.235668,-0.74335,-0.34222,-0.083157,0.47914,0.224335
2,-0.92,0.11,0.78,0.12,-0.03,-0.27,0.1,-0.04,1.13,-0.07,...,0.486026,-0.637347,0.468229,0.213356,0.234385,-0.741247,-0.337692,-0.081529,0.480035,0.223921
3,-0.84,0.09,0.89,0.12,-0.03,-0.28,0.1,-0.04,1.31,-0.07,...,0.490384,-0.638057,0.471164,0.215599,0.23535,-0.739957,-0.33979,-0.082308,0.477875,0.224014
4,-0.87,0.32,0.2,0.12,-0.03,-0.27,0.1,-0.04,1.21,-0.07,...,0.497087,-0.634704,0.470136,0.221407,0.237462,-0.741671,-0.337224,-0.082881,0.477551,0.226495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,-1.62,0.84,1.11,0.17,-0.14,0.4,0.12,-0.09,-0.48,-0.0,...,0.489441,-0.633794,0.470396,0.21542,0.231982,-0.738368,-0.333106,-0.081708,0.492607,0.226601
338,-1.17,1.72,-1.02,-0.03,-0.59,0.37,-0.01,-0.17,-0.32,-0.0,...,0.481819,-0.634161,0.479171,0.20591,0.232251,-0.735315,-0.317403,-0.081924,0.490603,0.230942
339,-1.3,0.01,1.18,0.17,-0.14,0.36,0.12,-0.09,-1.19,-0.0,...,0.488303,-0.622773,0.473042,0.207266,0.228895,-0.737881,-0.329442,-0.084764,0.493541,0.227497
340,-1.1,1.54,-1.21,0.17,-0.14,0.32,0.12,-0.09,-0.75,-0.0,...,0.489716,-0.632253,0.474812,0.21199,0.230123,-0.73251,-0.320594,-0.083481,0.483275,0.227804
341,-1.58,1.38,-0.33,0.17,-0.44,0.43,-0.2,-0.07,-0.33,-0.0,...,0.486336,-0.63014,0.477915,0.209096,0.226433,-0.740963,-0.327695,-0.084817,0.492529,0.227642

In [6]:
with open("ssm_tags.pickle", 'rb') as f:
    tags = pickle.load(f)

In [7]:
#tags = tags[:171]

In [8]:
df = pd.concat([predictions, tags], axis=1)

In [9]:
df['rank']=df[True].rank(axis=0, method="min", ascending=False)

In [10]:
df[0:171][df[0:171]['rank']<=20]

        False      True    id  rank
28   0.747102  0.252898  348H   7.0
32   0.752518  0.247482  348N  11.0
33   0.751599  0.248401  348A   8.0
37   0.752967  0.247033  348F  12.0
39   0.727681  0.272319  346W   3.0
134  0.737972  0.262027  305L   5.0
137  0.759428  0.240572  305H  15.0
141  0.736437  0.263563  305E   4.0
142  0.751678  0.248322  305C  10.0
161  0.763430  0.236570  306N  20.0
169  0.756498  0.243502  306V  13.0

In [11]:
df[171:][df[171:]['rank']<=20]

        False      True    id  rank
203  0.680961  0.319039  348N   1.0
230  0.751599  0.248401  346N   9.0
250  0.725332  0.274668  302I   2.0
256  0.759699  0.240301  302C  16.0
262  0.758012  0.241988  346V  14.0
271  0.746168  0.253832  346S   6.0
277  0.762166  0.237834  346P  18.0
305  0.763285  0.236715  305L  19.0
335  0.760993  0.239007  306S  17.0

In [12]:
df.to_excel("TZ-Y-all2-results.xlsx")