In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
from pandas import DataFrame

In [2]:
#load positive data id
pos_ids = defaultdict(list)
lines = open("../0.expdata/positive_hits.txt", 'r').readlines()
for l in lines:
    es = l.strip().split()
    pos_ids[es[0]].append(es[1])
print(pos_ids)
print(np.sum([len(l) for l in pos_ids.values()]))

defaultdict(<class 'list'>, {'A': ['A10', 'B1', 'B2', 'F11', 'F12', 'G1', 'G2', 'G3', 'G4', 'H1', 'H2', 'H3'], 'B': ['C7', 'C12', 'H1', 'H2', 'H3'], 'C': ['H1', 'H2', 'H3'], 'D': ['C4', 'H3'], 'E': ['C4', 'C7'], 'F': ['C4', 'D10', 'H1', 'H3'], 'G': ['B1', 'C5', 'C7', 'C9'], 'H': ['B1', 'E10', 'H4']})
35

In [3]:
#load energy data
all_data = pd.DataFrame()
for i in ["A","B","C","D","E","F","G","H"]:
    #print(i)
    df = pd.read_csv("ddg/train_U"+i+"_ddg_terms.txt", sep="\t", header=None)
    #delete all zero col
    df = df.loc[:,~(df==0).all(axis=0)]
    
    df['UAA'] = i
    df['label'] = [t in pos_ids[i] for t in df[0]]
    all_data = pd.concat([all_data, df], axis=0, ignore_index=True)
all_data = all_data.rename(columns={0: "id"})

In [4]:
#remove duplicates
all_data = all_data[all_data['id']!="D3" ]
all_data = all_data[all_data['id']!="G4" ]
all_data = all_data[all_data['id']!="E3" ]
all_data = all_data[all_data['id']!="C9" ]
all_data = all_data[all_data['id']!="Q5" ]
all_data = all_data[all_data['id']!="Q10" ]
all_data = all_data[all_data['id']!="D5" ]
all_data = all_data[all_data['id']!="A6" ]

In [6]:
all_data

,id,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,UAA,label
0,G7,-1.14,0.34,0.93,0.14,0.17,-0.27,0.05,-0.02,-0.00,...,-0.22,-0.23,0.22,-0.48,0.08,-0.34,0.03,-0.12,A,False
1,G6,-0.99,0.88,1.29,0.14,0.17,-0.17,0.05,-0.02,2.22,...,-0.05,-0.23,0.22,0.75,0.08,-0.10,0.03,-0.12,A,False
2,G5,-0.75,0.93,0.07,0.14,0.17,-0.34,0.05,-0.02,0.81,...,0.08,-0.23,0.22,-0.20,0.08,0.30,0.03,-0.12,A,False
4,G3,1.49,-1.99,-0.12,0.14,0.17,-0.28,0.05,-0.02,-2.27,...,0.01,-0.23,0.22,-0.24,0.08,-0.45,0.03,-0.12,A,True
5,G2,1.13,-1.76,0.45,0.14,0.17,-0.27,0.05,-0.02,-1.71,...,0.03,-0.23,0.22,-0.25,0.08,-0.67,0.03,-0.12,A,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,D6,-0.07,-0.48,0.18,0.13,-0.00,-0.38,-0.02,-0.13,-0.85,...,0.89,0.06,-0.11,-0.71,0.08,-0.63,-0.10,0.03,H,False
994,D7,-1.10,0.99,-1.52,-4.41,0.23,5.00,-0.56,-3.14,-1.97,...,-3.84,0.71,0.04,2.63,-4.91,-1.05,-4.06,4.66,H,False
995,D4,1.50,-1.71,0.34,0.13,-0.00,-0.12,-0.02,-0.13,-1.53,...,-2.67,0.06,-0.11,-0.29,0.08,0.23,-0.10,0.03,H,False
997,D2,0.60,0.65,-0.03,0.13,-0.00,0.45,-0.02,-0.13,1.05,...,0.25,0.06,-0.11,-0.80,0.08,0.59,-0.10,0.03,H,False
999,D1,-1.49,0.12,0.80,0.13,-0.00,0.38,-0.02,-0.13,-0.23,...,0.68,0.06,-0.11,0.12,0.08,-1.66,-0.10,0.03,H,False

In [7]:
#load ESM-1v, ESM-1b
df1v = pd.read_csv("../2.evotuning/mm_diskAB_1v_labeled.csv")
df1b = pd.read_csv("../2.evotuning/mm_diskAB_1b_labeled.csv")

In [8]:
all_data = pd.merge(all_data, df1v.loc[:, ['id','esm1v_t33_650M_UR90S_1']], how='left', on='id')
all_data = pd.merge(all_data, df1v.loc[:, ['id','esm1v_t33_650M_UR90S_2']], how='left', on='id')
all_data = pd.merge(all_data, df1v.loc[:, ['id','esm1v_t33_650M_UR90S_3']], how='left', on='id')
all_data = pd.merge(all_data, df1v.loc[:, ['id','esm1v_t33_650M_UR90S_4']], how='left', on='id')
all_data = pd.merge(all_data, df1v.loc[:, ['id','esm1v_t33_650M_UR90S_5']], how='left', on='id')
all_data = pd.merge(all_data, df1b.loc[:, ['id','esm_msa1b_t12_100M_UR50S']], how='left', on='id')

In [9]:
raw_data = all_data.copy()

In [10]:
#extract X
col = raw_data.columns.values.tolist()
col.remove('UAA')
col.remove('label')
col.remove('id')

In [12]:
X = np.array(raw_data[col])
y = np.array(raw_data['label'])

In [13]:
raw_data.columns.values.tolist()

['id',
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 'UAA',
 'label',
 'esm1v_t33_650M_UR90S_1',
 'esm1v_t33_650M_UR90S_2',
 'esm1v_t33_650M_UR90S_3',
 'esm1v_t33_650M_UR90S_4',
 'esm1v_t33_650M_UR90S_5',
 'esm_msa1b_t12_100M_UR50S']

In [14]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [15]:
#load eUnirep 256 embedding
evo_tag = "256"
evo_num = int(evo_tag)
from jax_unirep.evotuning_models import mlstm256
from jax_unirep.utils import load_params
from jax_unirep import get_reps

In [17]:
i2s = {}
lines = open("map_label_fname.txt", 'r')
for l in lines:
    es = l.strip().split()
    i2s[es[0]] = es[2]

In [18]:
sequences = [i2s[t] for t in i2s.keys()]
s2t = {i2s[t]:t for t in i2s.keys()}

In [19]:
params = load_params(folderpath='../2.evotuning/unirep/weights/'+evo_tag+'/', paper_weights=evo_num)[1]
h_avg, h_final, c_final= get_reps(sequences, params=params,mlstm_size=evo_num)

In [20]:
df_evo = pd.DataFrame()
for i, t in enumerate(i2s.keys()):
    d = pd.Series([s2t[sequences[i]]]+[x for x in h_avg[i]])
    assert(t == s2t[sequences[i]])
    df_evo = pd.concat([df_evo, d.to_frame().T], axis=0, ignore_index=True)

In [21]:
convert = {i:"e"+str(i) for i in range(1+evo_num)}
convert[0] = "id"
df_evo = df_evo.rename(columns=convert)

In [22]:
raw_data = pd.merge(all_data, df_evo.loc[:, :], how='left', on='id')

In [23]:
col = raw_data.columns.values.tolist()
#col.remove('tag')
col.remove('UAA')
col.remove('label')
col.remove('id')

In [24]:
X = np.array(raw_data[col])
y = np.array(raw_data['label'])

In [26]:
import pickle
with open("train_evo"+evo_tag+".pickle", 'wb') as f:
    pickle.dump([X, y], f)